export default [
    { id: 1, department: "Comps", semester: "Sem1", subject: "DBMS", note: "Note 1", name: "Shared By John", link: "https://somaiya0-my.sharepoint.com/:b:/g/personal/riddhesh_c_somaiya_edu/EcRm-4tjW15Ilq9HgcKiyHIBJBAZcq5FuM1XHnFAaYFmOQ?e=9h1CXT" },
    { id: 2, department: "AI-DS", semester: "Sem1", subject: "ML", note: "Note 2" },
    { id: 3, department: "IT", semester: "Sem1", subject: "OS", note: "Note 3" },
    { id: 4, department: "EXTC", semester: "Sem1", subject: "EC", note: "Note 4" },
    { id: 5, department: "Comps", semester: "Sem2", subject: "CN", note: "Note 5" },
    { id: 6, department: "AI-DS", semester: "Sem2", subject: "AI", note: "Note 6" },
    { id: 7, department: "IT", semester: "Sem2", subject: "DS", note: "Note 7" },
    { id: 8, department: "EXTC", semester: "Sem2", subject: "CA", note: "Note 8" },
    { id: 9, department: "Comps", semester: "Sem3", subject: "DC", note: "Note 9" },
    { id: 10, department: "AI-DS", semester: "Sem3", subject: "CV", note: "Note 10" },
    { id: 11, department: "IT", semester: "Sem3", subject: "CN", note: "Note 11" },
    { id: 12, department: "EXTC", semester: "Sem3", subject: "EC", note: "Note 12" },
    { id: 13, department: "Comps", semester: "Sem4", subject: "OS", note: "Note 13" },
    { id: 14, department: "AI-DS", semester: "Sem4", subject: "ML", note: "Note 14" },
    { id: 15, department: "IT", semester: "Sem4", subject: "DBMS", note: "Note 15" },
    { id: 16, department: "EXTC", semester: "Sem4", subject: "AI", note: "Note 16" },
  ];